#pragma once

//----------------------------------------------------------------------------
enum {
	OnMenuActionSave,
	OnMenuActionOpen,
	OnMenuActionVideoOption,
	OnMenuActionControlOption,
	OnMenuActionDamageOption,
	OnMenuActionAimOption,
	OnMenuActionOperationScreen,

	StartButtonClik,
	ResetHPButtonClik,
	ConnectButtonClik,
	VideoButtonClik,
	MouseControlButtonClik,

	EditIP,
	EditTimer,

	SearchWindowHandlesButtonClik,

	ID_COMPONENTSUSER,

	ID_LISTBOX_SearchWindowHandles,
	ClickButtonSearchWindowHandles,

	CheckBoxOptionWindowAction,
	EditOptionHeight,
	EditOptionWeight,
	EditOptionFramerate,
	EditOptionBitrate,
	EditOptionVideoPort,

	CheckBoxM1AccelerationSpeed,
	CheckBoxM2AccelerationSpeed,
	EditM1RotationLimit,
	EditM1RotationSpeedInt,
	EditM1RotationSpeedFrac,
	EditM1StepsStepperMotor,
	EditM1MicroStepsStepperMotor,
	EditM1ReductionRatioStepperMotorInt,
	EditM1ReductionRatioStepperMotorFrac,
	EditM1FreqSignal,
	EditM1PeriodSignal,
	EditM2RotationLimit,
	EditM2RotationSpeedInt,
	EditM2RotationSpeedFrac,
	EditM2StepsStepperMotor,
	EditM2MicroStepsStepperMotor,
	EditM2ReductionRatioStepperMotorInt,
	EditM2ReductionRatioStepperMotorFrac,
	EditM2FreqSignal,
	EditM2PeriodSignal,

	EditOptionHP,
	CheckBoxWeapoOff,
	CheckBoxMovementOff,
	CheckBoxVideoOff,
	EditOptionDelayDamageMinute,
	EditOptionDelayDamageSecunde,
	EditOptionDelaySensor_ms,

	EditOptionAimX,
	EditOptionAimY,
	EditOptionAimHeight,
	EditOptionAimWidth,
	EditOptionAimLineWidth,
	EditOptionAimTextWidth,
	EditOptionAimTextHeight,
	ButtonOptionAimColorText,
	CheckBoxText1,
	EditOptionOffsetText1,
	EditOptionLenLineText1,
	EditOptionText1,
	CheckBoxText2,
	EditOptionOffsetText2,
	EditOptionLenLineText2,
	EditOptionText2,
	CheckBoxText3,
	EditOptionOffsetText3,
	EditOptionLenLineText3,
	EditOptionText3,

	OnExitSoftware,
};

